apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobintel
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - configmap.yaml
  - secret.example.yaml
  - cronjob.yaml
  - job.manual.yaml
  - job.s3preflight.yaml
