apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../jobintel
patchesStrategicMerge:
  - patch-serviceaccount.yaml
  - patch-configmap.yaml
images:
  - name: ghcr.io/yourorg/jobintel
    newName: ghcr.io/yourorg/jobintel
    newTag: latest
