apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../onprem
  - traefik-dashboard-middleware.yaml
  - networkpolicy-dashboard.yaml
patchesStrategicMerge:
  - patch-ingress-dashboard-security.yaml
commonLabels:
  jobintel.io/overlay: onprem-pi
